const express = require('express')
const path = require('path')

/**
 * This file is just here for serving up the test report generated by Botium to the browser.
 * It uses the "Mochawesome" reporter (https://github.com/adamgruber/mochawesome)
 *
 * The "bot" directory contains a simple in-memory chatbot just returning some default texts, pictures and buttons
 * The "spec" directory contains the Botium convo files used to test the chatbot
 **/
const port = process.env.PORT || 8080
const app = express()
app.use(express.static(path.resolve(__dirname, 'mochawesome-report')))
app.get('*', function (request, response){
  response.sendFile(path.resolve(__dirname, 'mochawesome-report', 'mochawesome.html'))
})
app.listen(port)
console.log("server started on port " + port)
